apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001 #can access pods on the Node External IP:port
    protocol: TCP
  selector:
    app: hello-world