apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  ports:
  - port: 8080
  selector:
    app: hello-world   # Label selector
    # Service is looking for Pods with the label `app=hello-world`